CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20251215174252_Initial') THEN
    CREATE TABLE "AspNetRoles" (
        id text NOT NULL,
        name character varying(256),
        normalized_name character varying(256),
        concurrency_stamp text,
        CONSTRAINT pk_asp_net_roles PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20251215174252_Initial') THEN
    CREATE TABLE "AspNetUsers" (
        id text NOT NULL,
        user_name character varying(256),
        normalized_user_name character varying(256),
        email character varying(256),
        normalized_email character varying(256),
        email_confirmed boolean NOT NULL,
        password_hash text,
        security_stamp text,
        concurrency_stamp text,
        phone_number text,
        phone_number_confirmed boolean NOT NULL,
        two_factor_enabled boolean NOT NULL,
        lockout_end timestamp with time zone,
        lockout_enabled boolean NOT NULL,
        access_failed_count integer NOT NULL,
        CONSTRAINT pk_asp_net_users PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20251215174252_Initial') THEN
    CREATE TABLE data_protection_keys (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        friendly_name text,
        xml text,
        CONSTRAINT pk_data_protection_keys PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20251215174252_Initial') THEN
    CREATE TABLE "AspNetRoleClaims" (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        role_id text NOT NULL,
        claim_type text,
        claim_value text,
        CONSTRAINT pk_asp_net_role_claims PRIMARY KEY (id),
        CONSTRAINT fk_asp_net_role_claims_asp_net_roles_role_id FOREIGN KEY (role_id) REFERENCES "AspNetRoles" (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20251215174252_Initial') THEN
    CREATE TABLE "AspNetUserClaims" (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        user_id text NOT NULL,
        claim_type text,
        claim_value text,
        CONSTRAINT pk_asp_net_user_claims PRIMARY KEY (id),
        CONSTRAINT fk_asp_net_user_claims_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES "AspNetUsers" (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20251215174252_Initial') THEN
    CREATE TABLE "AspNetUserLogins" (
        login_provider text NOT NULL,
        provider_key text NOT NULL,
        provider_display_name text,
        user_id text NOT NULL,
        CONSTRAINT pk_asp_net_user_logins PRIMARY KEY (login_provider, provider_key),
        CONSTRAINT fk_asp_net_user_logins_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES "AspNetUsers" (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20251215174252_Initial') THEN
    CREATE TABLE "AspNetUserPasskeys" (
        credential_id bytea NOT NULL,
        user_id varchar(450) NOT NULL,
        data text NOT NULL,
        CONSTRAINT "PK_AspNetUserPasskeys" PRIMARY KEY (credential_id),
        CONSTRAINT "FK_AspNetUserPasskeys_AspNetUsers_UserId" FOREIGN KEY (user_id) REFERENCES "AspNetUsers" (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20251215174252_Initial') THEN
    CREATE TABLE "AspNetUserRoles" (
        user_id text NOT NULL,
        role_id text NOT NULL,
        CONSTRAINT pk_asp_net_user_roles PRIMARY KEY (user_id, role_id),
        CONSTRAINT fk_asp_net_user_roles_asp_net_roles_role_id FOREIGN KEY (role_id) REFERENCES "AspNetRoles" (id) ON DELETE CASCADE,
        CONSTRAINT fk_asp_net_user_roles_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES "AspNetUsers" (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20251215174252_Initial') THEN
    CREATE TABLE "AspNetUserTokens" (
        user_id text NOT NULL,
        login_provider text NOT NULL,
        name text NOT NULL,
        value text,
        CONSTRAINT pk_asp_net_user_tokens PRIMARY KEY (user_id, login_provider, name),
        CONSTRAINT fk_asp_net_user_tokens_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES "AspNetUsers" (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20251215174252_Initial') THEN
    CREATE INDEX ix_asp_net_role_claims_role_id ON "AspNetRoleClaims" (role_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20251215174252_Initial') THEN
    CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" (normalized_name);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20251215174252_Initial') THEN
    CREATE INDEX ix_asp_net_user_claims_user_id ON "AspNetUserClaims" (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20251215174252_Initial') THEN
    CREATE INDEX ix_asp_net_user_logins_user_id ON "AspNetUserLogins" (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20251215174252_Initial') THEN
    CREATE INDEX ix_asp_net_user_roles_role_id ON "AspNetUserRoles" (role_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20251215174252_Initial') THEN
    CREATE INDEX "EmailIndex" ON "AspNetUsers" (normalized_email);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20251215174252_Initial') THEN
    CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" (normalized_user_name);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20251215174252_Initial') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20251215174252_Initial', '10.0.1');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20251215183104_AddStory') THEN
    CREATE TABLE stories (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        title text NOT NULL,
        created_by_id text NOT NULL,
        CONSTRAINT pk_stories PRIMARY KEY (id),
        CONSTRAINT fk_stories_mass_identity_user_created_by_id FOREIGN KEY (created_by_id) REFERENCES "AspNetUsers" (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20251215183104_AddStory') THEN
    CREATE INDEX ix_stories_created_by_id ON stories (created_by_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20251215183104_AddStory') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20251215183104_AddStory', '10.0.1');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20251215191251_MoreColumns') THEN
    ALTER TABLE stories ADD created_at timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20251215191251_MoreColumns') THEN
    ALTER TABLE stories ADD description text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20251215191251_MoreColumns') THEN
    ALTER TABLE stories ADD last_modified_at timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20251215191251_MoreColumns') THEN
    ALTER TABLE "AspNetUsers" ADD story_id integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20251215191251_MoreColumns') THEN
    CREATE TABLE chapter (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        "order" integer NOT NULL,
        title text NOT NULL,
        created_at timestamp with time zone NOT NULL,
        last_modified_at timestamp with time zone NOT NULL,
        story_id integer NOT NULL,
        created_by_id text NOT NULL,
        CONSTRAINT pk_chapter PRIMARY KEY (id),
        CONSTRAINT fk_chapter_mass_identity_user_created_by_id FOREIGN KEY (created_by_id) REFERENCES "AspNetUsers" (id) ON DELETE CASCADE,
        CONSTRAINT fk_chapter_stories_story_id FOREIGN KEY (story_id) REFERENCES stories (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20251215191251_MoreColumns') THEN
    CREATE INDEX ix_asp_net_users_story_id ON "AspNetUsers" (story_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20251215191251_MoreColumns') THEN
    CREATE INDEX ix_chapter_created_by_id ON chapter (created_by_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20251215191251_MoreColumns') THEN
    CREATE INDEX ix_chapter_story_id ON chapter (story_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20251215191251_MoreColumns') THEN
    ALTER TABLE "AspNetUsers" ADD CONSTRAINT fk_asp_net_users_stories_story_id FOREIGN KEY (story_id) REFERENCES stories (id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20251215191251_MoreColumns') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20251215191251_MoreColumns', '10.0.1');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20251215192618_AddMoreTables') THEN
    ALTER TABLE chapter DROP CONSTRAINT fk_chapter_mass_identity_user_created_by_id;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20251215192618_AddMoreTables') THEN
    ALTER TABLE chapter DROP CONSTRAINT fk_chapter_stories_story_id;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20251215192618_AddMoreTables') THEN
    ALTER TABLE chapter DROP CONSTRAINT pk_chapter;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20251215192618_AddMoreTables') THEN
    ALTER TABLE chapter RENAME TO chapters;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20251215192618_AddMoreTables') THEN
    ALTER INDEX ix_chapter_story_id RENAME TO ix_chapters_story_id;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20251215192618_AddMoreTables') THEN
    ALTER INDEX ix_chapter_created_by_id RENAME TO ix_chapters_created_by_id;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20251215192618_AddMoreTables') THEN
    ALTER TABLE chapters ALTER COLUMN created_by_id DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20251215192618_AddMoreTables') THEN
    ALTER TABLE chapters ADD CONSTRAINT pk_chapters PRIMARY KEY (id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20251215192618_AddMoreTables') THEN
    CREATE TABLE entries (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        "order" integer NOT NULL,
        content text NOT NULL,
        created_at timestamp with time zone NOT NULL,
        last_modified_at timestamp with time zone NOT NULL,
        chapter_id integer NOT NULL,
        created_by_id text,
        CONSTRAINT pk_entries PRIMARY KEY (id),
        CONSTRAINT fk_entries_chapters_chapter_id FOREIGN KEY (chapter_id) REFERENCES chapters (id) ON DELETE CASCADE,
        CONSTRAINT fk_entries_mass_identity_user_created_by_id FOREIGN KEY (created_by_id) REFERENCES "AspNetUsers" (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20251215192618_AddMoreTables') THEN
    CREATE INDEX ix_entries_chapter_id ON entries (chapter_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20251215192618_AddMoreTables') THEN
    CREATE INDEX ix_entries_created_by_id ON entries (created_by_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20251215192618_AddMoreTables') THEN
    ALTER TABLE chapters ADD CONSTRAINT fk_chapters_mass_identity_user_created_by_id FOREIGN KEY (created_by_id) REFERENCES "AspNetUsers" (id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20251215192618_AddMoreTables') THEN
    ALTER TABLE chapters ADD CONSTRAINT fk_chapters_stories_story_id FOREIGN KEY (story_id) REFERENCES stories (id) ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20251215192618_AddMoreTables') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20251215192618_AddMoreTables', '10.0.1');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20251215193620_AddMoreRelations') THEN
    ALTER TABLE "AspNetUsers" DROP CONSTRAINT fk_asp_net_users_stories_story_id;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20251215193620_AddMoreRelations') THEN
    ALTER TABLE stories DROP CONSTRAINT fk_stories_mass_identity_user_created_by_id;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20251215193620_AddMoreRelations') THEN
    DROP INDEX ix_asp_net_users_story_id;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20251215193620_AddMoreRelations') THEN
    ALTER TABLE "AspNetUsers" DROP COLUMN story_id;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20251215193620_AddMoreRelations') THEN
    CREATE TABLE story_contributor (
        contributor_id text NOT NULL,
        story_id integer NOT NULL,
        CONSTRAINT pk_story_contributor PRIMARY KEY (contributor_id, story_id),
        CONSTRAINT fk_story_contributor_asp_net_users_contributor_id FOREIGN KEY (contributor_id) REFERENCES "AspNetUsers" (id) ON DELETE CASCADE,
        CONSTRAINT fk_story_contributor_stories_story_id FOREIGN KEY (story_id) REFERENCES stories (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20251215193620_AddMoreRelations') THEN
    CREATE INDEX ix_story_contributor_story_id ON story_contributor (story_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20251215193620_AddMoreRelations') THEN
    ALTER TABLE stories ADD CONSTRAINT fk_stories_asp_net_users_created_by_id FOREIGN KEY (created_by_id) REFERENCES "AspNetUsers" (id) ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20251215193620_AddMoreRelations') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20251215193620_AddMoreRelations', '10.0.1');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20251216015607_AddIsStoryPublic') THEN
    ALTER TABLE stories ADD is_public boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20251216015607_AddIsStoryPublic') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20251216015607_AddIsStoryPublic', '10.0.1');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20251216183626_AddStoryInvites') THEN
    CREATE TABLE story_invites (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        created_at timestamp with time zone NOT NULL,
        accepted_at timestamp with time zone,
        story_id integer NOT NULL,
        invited_user_id text NOT NULL,
        invited_by_id text NOT NULL,
        CONSTRAINT pk_story_invites PRIMARY KEY (id),
        CONSTRAINT fk_story_invites_mass_identity_user_invited_by_id FOREIGN KEY (invited_by_id) REFERENCES "AspNetUsers" (id) ON DELETE CASCADE,
        CONSTRAINT fk_story_invites_mass_identity_user_invited_user_id FOREIGN KEY (invited_user_id) REFERENCES "AspNetUsers" (id) ON DELETE CASCADE,
        CONSTRAINT fk_story_invites_stories_story_id FOREIGN KEY (story_id) REFERENCES stories (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20251216183626_AddStoryInvites') THEN
    CREATE INDEX ix_story_invites_invited_by_id ON story_invites (invited_by_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20251216183626_AddStoryInvites') THEN
    CREATE INDEX ix_story_invites_invited_user_id ON story_invites (invited_user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20251216183626_AddStoryInvites') THEN
    CREATE INDEX ix_story_invites_story_id ON story_invites (story_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20251216183626_AddStoryInvites') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20251216183626_AddStoryInvites', '10.0.1');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20251216191510_MakeIsAcceptedAColumn') THEN
    ALTER TABLE story_invites ADD is_accepted boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20251216191510_MakeIsAcceptedAColumn') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20251216191510_MakeIsAcceptedAColumn', '10.0.1');
    END IF;
END $EF$;
COMMIT;

